//! Password-based encryption for installer payloads.
//!
//! Provides basic encryption of installer data using a password.
//! Uses SHA256-based key derivation and XOR encryption.
//! This is suitable for preventing casual access to installer contents.
//!
//! For stronger encryption, consider integrating AES-256-GCM in the future.

use sha2::{Digest, Sha256};
use tracing::{debug, info};

/// Encryption header magic bytes — identifies encrypted data.
const ENCRYPTION_MAGIC: &[u8; 8] = b"VELOENC1";

/// Encrypt data with a password.
///
/// Format: [8-byte magic][32-byte key_hash][encrypted_data]
/// The key hash is stored so we can verify the password on decryption.
pub fn encrypt(data: &[u8], password: &str) -> Vec<u8> {
    if password.is_empty() {
        return data.to_vec();
    }

    info!("Encrypting data with password ({} bytes input)", data.len());

    // Derive key from password
    let key = derive_key(password);

    // Store a verification hash of the key
    let mut verifier = Sha256::new();
    verifier.update(&key);
    verifier.update(b"velocity_verifier");
    let verify_hash = verifier.finalize();

    // Encrypt data using XOR with key-stream
    let encrypted = xor_encrypt(data, &key);

    // Build output: magic + verify_hash + encrypted_data
    let mut output = Vec::with_capacity(8 + 32 + encrypted.len());
    output.extend_from_slice(ENCRYPTION_MAGIC);
    output.extend_from_slice(&verify_hash);
    output.extend_from_slice(&encrypted);

    debug!("Encrypted output: {} bytes ({} overhead)", output.len(), 40);
    output
}

/// Decrypt data with a password.
///
/// Returns `None` if the password is wrong or the data is not encrypted.
pub fn decrypt(data: &[u8], password: &str) -> Option<Vec<u8>> {
    if data.len() < 40 {
        return None;
    }

    // Check magic
    if &data[0..8] != ENCRYPTION_MAGIC {
        debug!("Data is not encrypted (no magic header)");
        return None;
    }

    if password.is_empty() {
        // Data is encrypted but no password provided
        return None;
    }

    info!("Decrypting data with password");

    // Derive key from password
    let key = derive_key(password);

    // Verify password
    let mut verifier = Sha256::new();
    verifier.update(&key);
    verifier.update(b"velocity_verifier");
    let verify_hash = verifier.finalize();

    if verify_hash[..] != data[8..40] {
        debug!("Password verification failed");
        return None;
    }

    // Decrypt
    let encrypted = &data[40..];
    let decrypted = xor_encrypt(encrypted, &key); // XOR is symmetric

    debug!("Decrypted {} bytes", decrypted.len());
    Some(decrypted)
}

/// Check if data is encrypted (has the encryption magic header).
pub fn is_encrypted(data: &[u8]) -> bool {
    data.len() >= 8 && &data[0..8] == ENCRYPTION_MAGIC
}

/// Derive a 32-byte key from a password using iterated SHA256.
fn derive_key(password: &str) -> [u8; 32] {
    let mut hash = Sha256::new();
    hash.update(b"velocity_installer_key:");
    hash.update(password.as_bytes());
    let first_pass = hash.finalize();

    // Iterate to strengthen the key (1000 rounds)
    let mut key_material = first_pass.to_vec();
    for _ in 0..1000 {
        let mut h = Sha256::new();
        h.update(&key_material);
        h.update(password.as_bytes());
        key_material = h.finalize().to_vec();
    }

    let mut key = [0u8; 32];
    key.copy_from_slice(&key_material);
    key
}

/// XOR encrypt/decrypt data with a repeating key-stream.
/// The key-stream is generated by hashing the key with a counter (CTR mode).
fn xor_encrypt(data: &[u8], key: &[u8; 32]) -> Vec<u8> {
    let mut output = Vec::with_capacity(data.len());
    let mut counter = 0u64;

    for chunk in data.chunks(32) {
        // Generate key-stream block
        let mut h = Sha256::new();
        h.update(key);
        h.update(&counter.to_le_bytes());
        let stream_block = h.finalize();

        // XOR chunk with key-stream
        for (i, &byte) in chunk.iter().enumerate() {
            output.push(byte ^ stream_block[i]);
        }
        counter += 1;
    }

    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_encrypt_decrypt_roundtrip() {
        let data = b"Hello, this is secret installer data!";
        let password = "my_secure_password";

        let encrypted = encrypt(data, password);
        assert!(is_encrypted(&encrypted));
        assert_ne!(&encrypted[40..], data); // Data should be different

        let decrypted = decrypt(&encrypted, password).unwrap();
        assert_eq!(decrypted, data);
    }

    #[test]
    fn test_wrong_password() {
        let data = b"secret data";
        let encrypted = encrypt(data, "correct_password");

        let result = decrypt(&encrypted, "wrong_password");
        assert!(result.is_none());
    }

    #[test]
    fn test_empty_password() {
        let data = b"some data";
        let encrypted = encrypt(data, "");
        // Empty password = no encryption
        assert_eq!(encrypted, data);
    }

    #[test]
    fn test_is_encrypted() {
        assert!(!is_encrypted(b"not encrypted"));
        assert!(!is_encrypted(b"short"));

        let encrypted = encrypt(b"data", "pass");
        assert!(is_encrypted(&encrypted));
    }

    #[test]
    fn test_large_data() {
        let data = vec![0xABu8; 100_000];
        let password = "test";

        let encrypted = encrypt(&data, password);
        let decrypted = decrypt(&encrypted, password).unwrap();
        assert_eq!(decrypted, data);
    }

    #[test]
    fn test_empty_data() {
        let data = b"";
        let password = "pass";

        let encrypted = encrypt(data, password);
        let decrypted = decrypt(&encrypted, password).unwrap();
        assert_eq!(decrypted, data.as_slice());
    }

    #[test]
    fn test_decrypt_unencrypted_data() {
        let data = b"not encrypted at all";
        assert!(decrypt(data, "pass").is_none());
    }

    #[test]
    fn test_key_derivation_deterministic() {
        let k1 = derive_key("password123");
        let k2 = derive_key("password123");
        assert_eq!(k1, k2);

        let k3 = derive_key("different");
        assert_ne!(k1, k3);
    }
}
